### ISSUE TITLE
bsb compilation fails with bs-moment installed in project

### ISSUE THREAD

**Issue by ferakpeter** [BuckleTypes/bs-moment#6]
Hi! 

we're getting this issue for a project that we're doing, and it appeared on a few machines, so looks like something is broken with the bs-moment npm install. I tracked down that the bsconfig.json is missing in the published NPM package, could this be an issue? From my understanding the package is installed then compiled with the bsb compiler and then used by the bsb compiler to create the package. The error we get is:

> Package not found: resolving package bs-moment in /  
Fatal error: exception BuckleScript package bs-moment not found or built , if it is not built
Please run 'bsb -make-world', otherwise please install it 
Error happened when running command /Users/fp/code/examples/reason/website-fp-fork/node_modules/bs-platform/bin/bsb.exe with args [ '-make-world', '-w' ]

When I ran bsb -make-world on the npm folder it complained that bsconfig.json is missing. 

The steps to reproduce are:

1. Set up empty bucklescript project (bs-platform)
2. npm install
3. bsb -make-world

**Comment by Jimexist** [comment]
@ferakpeter thanks for the issue - i republished a newer version, do you mind trying that?

**Comment by ferakpeter** [comment]
Looks good! Thanks a lot, please close the issue.

**Comment by Jimexist** [comment]
@ferakpeter feel free to file an issue if you discover more problems
